config/routes.rb
Rails.application.routes.draw do
  get 'git_srch/index'
  root 'git_srch#index'
  get 'git_srch/display'
  get 'git_srch/first'
  get 'git_srch/last'
  get 'git_srch/next'
  get 'git_srch/previous'
  get 'git_srch/go'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/git_srch_controller.rb
class GitSrchController < ApplicationController
  require 'open-uri'
  def index
  end

  def go
  	session[:search] = params[:search]
  	session[:page] = 1
  	redirect_to git_srch_display_path
  end	

  def next
  	session[:page] = session[:page] + 1
  	redirect_to git_srch_display_path
  end

  def previous
  	session[:page] = session[:page] - 1
  	if(session[:page] == 0)
  		session[:page] = 1
  	end	
  	redirect_to git_srch_display_path
  end

  def first
  	session[:page] = 1
  	redirect_to git_srch_display_path
  end

  def last
  	a=JSON.parse(open("https://api.github.com/search/users?q="+session[:search]).read)
  	session[:page] = (a['total_count'] / 30).to_i
  	redirect_to git_srch_display_path
  end

  def display
  	a=open("https://api.github.com/search/users?q="+session[:search]+"&page="+session[:page].to_s).read
  	b=JSON.parse(a) 	
  	@users = b['items']
  end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/git_srch_helper.rb
module GitSrchHelper
end

app/views/git_srch/display.html.erb
<div class="container text-center" style="width: 70%;">
	<div class="row">
		<div class="col-xs-6">
			<h2>Page Number :<%=session[:page]%></h2>		
		</div>
		<div class="col-xs-6" style="padding: 10px;">
			<a href="<%=root_path %>" type="button" class="btn btn-primary">Search Others</a>		
		</div>
	</div> 		
	<table class="table-bordered" style="width: 100%;">
		<tr>	
			<th  class="text-center">Sl No.</th>
			<th  class="text-center">Name</th>
		</tr>	
		<% @users.each_with_index do |user, index| %>
			<tr class='text-center'>
				<td><h5> <%= index + 1%></h5></td>
				<td><a href="<%=user['html_url']%>" target='_blank'><h5><%=user['login'] %></h5></a></td>
			</tr>
		<%end%>	
	</table>
	<nav aria-label="...">
	  <ul class="pager">
	  	<li><a href="<%= git_srch_first_path %>">First</a></li>
	    <li><a href="<%= git_srch_previous_path %>">Previous</a></li>
	    <li><a href="<%= git_srch_next_path %>">Next</a></li>
	    <li><a href="<%= git_srch_last_path %>">Last</a></li>
	  </ul>
	</nav>
</div>	

app/views/git_srch/index.html.erb
<div class="container" style="max-width: 60%;">
  <div class="col-xs-12" >
    <form action="git_srch/go">
      <div class="input-group">
        <input type="text" class="form-control" name="search" placeholder="Search for...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="submit">Go!</button>
        </span>
      </div>
    </form>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GitSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>